### ISSUE TITLE
refresh page 404 error

### ISSUE THREAD

**Issue by palec87** [Unisergius/bluehack-vuejsproto#17]
If you refresh the page once outside of `home`, any https://codeblue.pt/....

file not found 404 error on from github pages is raised.

Accessing directly
https://codeblue.pt/eventInfo
also does not work

This is probably the issue, but I know little about serving pages
https://v3.router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by Unisergius** [comment]
Changed the github actions yml script to clone the compiled index.html into a 404.html. Tested, it worked.

**Comment by palec87** [comment]
Cool @Unisergius, not sure how that small change would take me to find, ages for sure:)

**Comment by Unisergius** [comment]
It's essentially a problem specifically with github pages and vue router
